---
spring:
  profiles: default
  application:
    name: vehicledata-ws
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database_platform: org.hibernate.dialect.PostgreSQL9Dialect
    naming_strategy: org.hibernate.cfg.DefaultNamingStrategy

swagger.enabled: true
springfox.documentation.swagger.v2.path: /public/api-docs/

service:
  name: ${spring.application.name}
  database-name: vehicledata

#== Environment setup ==
environment:
  postgres:
    host: postgres
    port: 5432

#server configuration
server:
  port: 8080
  contextPath: /${spring.application.name}

session.timeout-mins: 1000

hikari:
  jdbcUrl: jdbc:postgresql://${environment.postgres.host}:${environment.postgres.port}/${service.database-name}
  username: postgres
  password:
  minimumIdle: 10
  maximumPoolSize: 10

info:
  app:
    name: Ajoneuvojen tekniset tiedot
    description: ${info.app.name}, TraFin avointa dataa hyödyntävä palvelu.
    version: 0.1.0

# group all management endpoints under a single path
management:
  port: 1${server.port}
  add-application-context-header: false

# Actuator endpoints
# autoconfig, beans, configprops, dump, env, health, info, metrics, mappings, shutdown, trace
management.security.enabled: false
endpoints.health.sensitive: true # Mark if the endpoint exposes sensitive information.
management.health:
 db.enabled: true # Enable database health check.
 defaults.enabled: true # Enable default health indicators.
 diskspace.enabled: true # Enable disk space health check.

logging.level:
  com.ruleoftech.vehicledata: DEBUG
  org.springframework: WARN
  org.apache.cxf: INFO

---
spring:
  profiles: local


hikari:
  jdbcUrl: jdbc:postgresql://localhost:5432/${service.database-name}
  username: postgres
  password: postgres
  minimumIdle: 10
  maximumPoolSize: 10